name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello"
    - run: | 
        dotnet --version
        dotnet build --configuration Release HelloWorld
        echo "Build Successfully"
        
