name: learn-github-actions
on: [push]
jobs:
  build-pipeline:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello"
    - run: | 
        dotnet --version
        dotnet restore
        dotnet build --configuration Release HelloWorld
        echo "Build Successfully"
        
