name: pipeline
on: [push]
jobs:
  build-pipeline:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello"
    - run: | 
        dotnet --version
        dotnet restore https://github.com/RhuddhiGawas02/WorkFlow/tree/main/AzureFunctionHttp
        echo "Restore Successfully"
        dotnet build https://github.com/RhuddhiGawas02/WorkFlow/tree/main/AzureFunctionHttp
        echo "Build Successfully"
        
