name: pipeline
on: [push]
jobs:
  build-pipeline:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello"
    - run: | 
        dotnet --version
        dotnet restore AzureFunctionHttp
        echo "Restore Successfully"
        dotnet build AzureFunctionHttp
        echo "Build Successfully"
        
